# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~
        main:
            pattern: ^/
            anonymous: true
            
    role_hierarchy:
        ROLE_WRITER: ROLE_READER
        ROLE_ADMIN: ROLE_WRITER
        
    access_control:
        - { path: ^/images, roles: ROLE_WRITER, methods: [POST] }
        - { path: /images, roles: ROLE_WRITER, methods: [PUT, PATCH] }
        - { path: /images, roles: ROLE_ADMIN, methods: [DELETE] }

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12